-- =========================
-- ENUM TYPES
-- =========================

CREATE TYPE language_enum AS ENUM ('UKR', 'ENG', 'FRA', 'GER', 'RUS');

CREATE TYPE order_status_enum AS ENUM (
    'Нове',
    'Прийняте',
    'В процесі доставки',
    'У відділі',
    'Виконане',
    'Скасоване'
);

CREATE TYPE payment_status_enum AS ENUM (
    'Не оплачено',
    'Оплачено',
    'Помилка оплати'
);

CREATE TYPE sale_status_enum AS ENUM (
    'Без знижки',
    'Зі знижкою'
);


-- =========================
-- ADMINISTRATIVE TABLES
-- =========================

CREATE TABLE Roles (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE Users (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(30) UNIQUE NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role_id INT NOT NULL REFERENCES Roles(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- =========================
-- MAIN TABLES
-- =========================

CREATE TABLE Publishers (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    description TEXT NOT NULL
);

CREATE TABLE Books (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    language language_enum NOT NULL,
    isbn VARCHAR(17) UNIQUE NOT NULL,
    publication_year INT CHECK (publication_year >= 0) NOT NULL,
    publisher_id INT NOT NULL REFERENCES Publishers(id),
    quantity INT CHECK (quantity >= 0) NOT NULL,
    price NUMERIC(10,2) CHECK (price >= 0) NOT NULL,
    sale_status sale_status_enum NOT NULL,
    page_amount INT CHECK (page_amount > 0)
);

CREATE TABLE Authors (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    patronym VARCHAR(50),
    description TEXT NOT NULL
);

CREATE TABLE Genres (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(20) NOT NULL
);

CREATE TABLE Thematics (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(30) NOT NULL
);

CREATE TABLE Reviews (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    rating INT CHECK (rating BETWEEN 1 AND 5) NOT NULL,
    user_id INT NOT NULL REFERENCES Users(id) ON DELETE CASCADE,
    book_id INT NOT NULL REFERENCES Books(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, book_id)
);


-- =========================
-- MANY-TO-MANY TABLES
-- =========================

CREATE TABLE Favorites (
    user_id INT NOT NULL REFERENCES Users(id) ON DELETE CASCADE,
    book_id INT NOT NULL REFERENCES Books(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, book_id)
);

CREATE TABLE BookGenres (
    book_id INT NOT NULL REFERENCES Books(id) ON DELETE CASCADE,
    genre_id INT NOT NULL REFERENCES Genres(id) ON DELETE CASCADE,
    PRIMARY KEY (book_id, genre_id)
);

CREATE TABLE BookThematics (
    book_id INT NOT NULL REFERENCES Books(id) ON DELETE CASCADE,
    theme_id INT NOT NULL REFERENCES Thematics(id) ON DELETE CASCADE,
    PRIMARY KEY (book_id, theme_id)
);

CREATE TABLE BookAuthors (
    book_id INT NOT NULL REFERENCES Books(id) ON DELETE CASCADE,
    author_id INT NOT NULL REFERENCES Authors(id) ON DELETE CASCADE,
    PRIMARY KEY (book_id, author_id)
);


-- =========================
-- ORDER SYSTEM
-- =========================

CREATE TABLE Orders (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    delivery_address TEXT NOT NULL,
    order_status order_status_enum NOT NULL,
    user_id INT NOT NULL REFERENCES Users(id) ON DELETE RESTRICT,
    payment_status payment_status_enum NOT NULL,
    total_cost NUMERIC(10,2) CHECK (total_cost >= 0) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OrderBooks (
    order_id INT NOT NULL REFERENCES Orders(id) ON DELETE CASCADE,
    book_id INT NOT NULL REFERENCES Books(id) ON DELETE RESTRICT,
    price_at_sale NUMERIC(10,2) CHECK (price_at_sale >= 0) NOT NULL,
    quantity INT CHECK (quantity > 0) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (order_id, book_id)
);


-- =========================
-- CART SYSTEM
-- =========================

CREATE TABLE Carts (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL UNIQUE REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE CartItems (
    cart_id INT NOT NULL REFERENCES Carts(id) ON DELETE CASCADE,
    book_id INT NOT NULL REFERENCES Books(id) ON DELETE CASCADE,
    quantity INT CHECK (quantity > 0) NOT NULL,
    PRIMARY KEY (cart_id, book_id)
);


-- =========================
-- PERFORMANCE INDEXES
-- =========================

CREATE INDEX idx_books_publisher ON Books(publisher_id);
CREATE INDEX idx_reviews_book ON Reviews(book_id);
CREATE INDEX idx_reviews_user ON Reviews(user_id);
CREATE INDEX idx_orders_user ON Orders(user_id);